### ISSUE TITLE
not work anymore without any change - ErrorCode="103"

### ISSUE THREAD

**Issue by MaurizioB84** [SebastianOsinski/HomebridgePluginSamsungAirConditioner#23]
Hi,

after 3 days of work now doesn't work anymore without any reason, I cannot see anything in the logs:
homebridge_1      | [8/9/2019, 11:04:30 AM] [Climatizzatore Camera] Getting active...
homebridge_1      | [8/9/2019, 11:04:32 AM] [Climatizzatore Camera] Setting active: 1
homebridge_1      | [8/9/2019, 11:08:15 AM] [Climatizzatore Camera] Getting target temperature...
homebridge_1      | [8/9/2019, 11:08:15 AM] [Climatizzatore Camera] Getting target state...
homebridge_1      | [8/9/2019, 11:08:15 AM] [Climatizzatore Camera] Getting target temperature...
homebridge_1      | [8/9/2019, 11:08:15 AM] [Climatizzatore Camera] Getting active...
homebridge_1      | [8/9/2019, 11:08:15 AM] [Climatizzatore Camera] Getting current temperature...
homebridge_1      | [8/9/2019, 11:08:15 AM] [Climatizzatore Camera] Getting swing mode...
homebridge_1      | [8/9/2019, 11:08:15 AM] [Climatizzatore Camera] Getting rotation speed...

I enable also the "log_socket_activity": "true", in the config file but never new log string found.

this is my config:
    "accessories": [
        {
            "accessory": "Samsung Air Conditioner",
            "name": "Climatizzatore Camera",
            "ip_address": "192.168.2.89",
            "mac": "78:25:AD:12:43:F7",
            "log_socket_activity": "true",
            "token": "33965903-4482-M849-N716-373832354144"
        },

**Comment by SebastianOsinski** [comment]
Hey, first thing you can try is to disconnect your AC unit from power and connect it again. I noticed strange this behavior in my unit, that after some long time it refuses to keep connection with plugin and only restart helps.

**Comment by SebastianOsinski** [comment]
`log_socket_activity` should be set to `true`, not `"true"` (quotation marks matter). With that setting you should see some socket errors, If I remember correctly ECONREFUSED or something similar.

**Comment by MaurizioB84** [comment]
you already tried keep_alive? maybe it's needed to close to socket...

**Comment by MaurizioB84** [comment]
homebridge_1      | [8/9/2019, 11:55:21 AM] [Climatizzatore Camera] Connected
homebridge_1      | [8/9/2019, 11:55:21 AM] [Climatizzatore Camera] Read: DRC-1.00
homebridge_1      | [8/9/2019, 11:55:21 AM] [Climatizzatore Camera] Read: <?xml version="1.0" encoding="utf-8" ?><Update Type="InvalidateAccount"/>
homebridge_1      | [8/9/2019, 11:55:21 AM] [Climatizzatore Camera] Auth request received - Authenticating...
homebridge_1      | [8/9/2019, 11:55:21 AM] [Climatizzatore Camera] Write: <Request Type="AuthToken"><User Token="33965903-4482-M849-N716-373832354144"/></Request>
homebridge_1      | [8/9/2019, 11:55:21 AM] [Climatizzatore Camera] Read: <?xml version="1.0" encoding="utf-8" ?><Response Type="AuthToken" Status="Okay" StartFrom="2019-08-09/09:55:20"/>
homebridge_1      | [8/9/2019, 11:55:21 AM] [Climatizzatore Camera] Authentication succeeded
homebridge_1      | [8/9/2019, 11:55:21 AM] [Climatizzatore Camera] Requesting full state summary...
homebridge_1      | [8/9/2019, 11:55:21 AM] [Climatizzatore Camera] Write: <Request Type="DeviceState" DUID="7825AD1243F7"></Request>
homebridge_1      | [8/9/2019, 11:55:21 AM] [Climatizzatore Camera] Read: <?xml version="1.0" encoding="utf-8" ?><Response Status="Fail" Type="DeviceState" ErrorCode="103" />
homebridge_1      | [8/9/2019, 11:55:19 AM] [Climatizzatore Camera] Connecting...
homebridge_1      | [8/9/2019, 11:55:21 AM] [Climatizzatore Camera] Connected
homebridge_1      | [8/9/2019, 11:55:21 AM] [Climatizzatore Camera] Read: DRC-1.00
homebridge_1      | [8/9/2019, 11:55:21 AM] [Climatizzatore Camera] Read: <?xml version="1.0" encoding="utf-8" ?><Update Type="InvalidateAccount"/>
homebridge_1      | [8/9/2019, 11:55:21 AM] [Climatizzatore Camera] Auth request received - Authenticating...
homebridge_1      | [8/9/2019, 11:55:21 AM] [Climatizzatore Camera] Write: <Request Type="AuthToken"><User Token="33965903-4482-M849-N716-373832354144"/></Request>
homebridge_1      | [8/9/2019, 11:55:21 AM] [Climatizzatore Camera] Read: <?xml version="1.0" encoding="utf-8" ?><Response Type="AuthToken" Status="Okay" StartFrom="2019-08-09/09:55:20"/>
homebridge_1      | [8/9/2019, 11:55:21 AM] [Climatizzatore Camera] Authentication succeeded
homebridge_1      | [8/9/2019, 11:55:21 AM] [Climatizzatore Camera] Requesting full state summary...
homebridge_1      | [8/9/2019, 11:55:21 AM] [Climatizzatore Camera] Write: <Request Type="DeviceState" DUID="7825AD1243F7"></Request>
homebridge_1      | [8/9/2019, 11:55:21 AM] [Climatizzatore Camera] Read: <?xml version="1.0" encoding="utf-8" ?><Response Status="Fail" Type="DeviceState" **ErrorCode="103" /**>

**Comment by SebastianOsinski** [comment]
Hi, sorry for the delay. From your log it looks like some kind of device error. TBH it's hard for me to advise anything in that case.
