### ISSUE TITLE
Request for other Aircon Brands

### ISSUE THREAD

**Issue by mitch7391** [SebastianOsinski/HomebridgePluginSamsungAirConditioner#25]
This probably isn’t the best place to post this, but wondering if you would be able to work on the E-zone Controller by Ambience/Advantage Air (uses E-zone app)? I would love to get a Homebridge plug-in for this but don’t have the know how. 

Another person who contacted me has created individual switches for each function of the AC through HTTP commands.

![103800A3-15EA-4991-9F41-E25952569188](https://user-images.githubusercontent.com/40288237/63508659-f576e500-c50c-11e9-89df-39614c71aa95.jpeg)
![EB91E406-8C40-4706-9A07-97733A6BA74B](https://user-images.githubusercontent.com/40288237/63508662-f60f7b80-c50c-11e9-8de2-5ad8912e5515.png)

**Comment by SebastianOsinski** [comment]
Hi. I won't be able to do that. It would be pretty hard to develop without having access to the hardware to test it on. Hope you find someone with know-how to develop this for you. I spoke about developing Homebridge plugins few months ago. You might find these materials helpful: [Slides](https://github.com/SebastianOsinski/LetSwiftSlides/blob/master/macbulb/macbulb.pdf) and [Example plugin](https://github.com/SebastianOsinski/MacBulb/tree/master/MacBulbHomebridgePlugin)

**Comment by mitch7391** [comment]
No worries :) thank you for the slides, I’ll have a read over them and see if I can learn anything.
