### ISSUE TITLE
It works but not all options available

### ISSUE THREAD

**Issue by SanderBaron** [SebastianOsinski/HomebridgePluginSamsungAirConditioner#26]
First of all, thanks for your work to share this amazing plugin with us! I have a Samsung multisplit with four units in my house and I really hated the Samsung app! This makes life a lot easier and more fun! I'm new to this HomeBridge game, but I Googled my way in to it and managed to have it up and running.

Although I still have some questions I successfully tested it on models:
- AR07HSSDBWKN
- AR09HSSDBWKN

My questions are:
My AC has 5 different operation modes: Auto, Cool, Heat, Dry and Fan.
In HomeKit I can only select Auto, Cool, Heat and Off. Dry and Fan can't be selected.

I can set the Fan speed with a slider on my iPhone in the Home.app. How to set it to "Auto"? Also when I set the slider to zero (all the way to the left), the AC is shut down. I think this is a bug?

My wall units are the high end units with some extra settings like "Comfort Mode", "Quiet Mode" and "Virus Doctor". Is there a way to make this available in the settings page?
Especially "Comfort Mode" and "Virus Doctor" we use every night in the kids rooms and we now have to set it manually with the remote or the stupid Samsung app..

**Comment by SebastianOsinski** [comment]
Hi!

All devices in HomeKit are standardized -  they have predefined options, so it's unfortunately not possible to add Dry and Fan to operation modes. HomeKit devices can support additional functionalities but to operate them, you would need dedicated app, which kind of misses the point ;). 
AFAIK, setting fan to 0 and AC getting shut down is not a bug, it's just inner logic of HomeKit. It sends shut down command when fan speed is set to 0.

I am also not aware of option to add Comfort, Quiet and Virus Doctor modes to settings page. It's the same reason as for Dry and Fan modes.
