### ISSUE TITLE
homebridge-samsung-ac-get-token not work 

### ISSUE THREAD

**Issue by wifi75** [SebastianOsinski/HomebridgePluginSamsungAirConditioner#27]
hello I want to get my token , I don't know but this command from the terminal homebridge-samsung-ac-get-token 192.168.1.213 not work.
why?

**Comment by SebastianOsinski** [comment]
Hi @wifi75 ! Could you provide some more information? What does exactly mean it doesn't work? What kind of error do you get? Have you installed the plugin successfully with npm?

**Comment by wifi75** [comment]
please hel me.... send me instruction step by step for  the command line for get token ID

**Comment by SebastianOsinski** [comment]
@wifi75 I need you to answer questions I asked in my previous comment to be able to help you. There is a step by step instruction in project's README.

**Comment by wifi75** [comment]
@SebastianOsinski yes already read but when tryed to send this command on the raspberry terminal  homebridge-samsung-ac-get-token 192.168.1.213 see attachment
![error](https://user-images.githubusercontent.com/31816231/66892362-c13f1280-efeb-11e9-88eb-674a277f44e2.JPG)
ch

**Comment by SebastianOsinski** [comment]
Have you installed plugin with `npm install -g homebridge-plugin-samsung-air-conditioner`? Because this command is part of the plugin.

**Comment by wifi75** [comment]
@SebastianOsinski see below
![npn](https://user-images.githubusercontent.com/31816231/66894616-3234f900-eff1-11e9-8e2c-ed8f9db77630.JPG)

**Comment by SebastianOsinski** [comment]
So your npm fails to install the plugin. Firstly, try running command with sudo:
`sudo npm install -g homebridge-plugin-samsung-air-conditioner`
If that does not help, then I would try fixing the warning about npm not supporting Node.js version you have. According to this topic: https://www.raspberrypi.org/forums/viewtopic.php?t=245989 it's Raspbian's problem. Reinstall matching npm version with:
`curl https://www.npmjs.com/install.sh | sudo sh`

And then try again `npm install -g homebridge-plugin-samsung-air-conditioner` or `sudo npm install -g homebridge-plugin-samsung-air-conditioner`

**Comment by wifi75** [comment]
I tryed ti install again with command curl https://www.npmjs.com/install.sh | sudo sh
after command sudo npm install -g homebridge-plugin-samsung-air-conditioner
maybe the same problem:

![Cattura](https://user-images.githubusercontent.com/31816231/66897349-1af90a00-eff7-11e9-9b3a-6e3f45ce4a4c.JPG)

**Comment by wifi75** [comment]
please tell me the compatible node version, I try to install that

**Comment by wifi75** [comment]
Yupiiiiiiiiii I have found my token follow this step:

wget https://nodejs.org/dist/v6.0.0/node-v6.0.0-linux-armv7l.tar.gz 
tar -xvf node-v6.0.0-linux-armv7l.tar.gz 
cd node-v64.0.0-linux-armv7l
sudo cp -R * /usr/local/

very good !!!!
