### ISSUE TITLE
Enhancement: Would it be possible to add fan speed control?

### ISSUE THREAD

**Issue by peros550** [SebastianOsinski/HomebridgePluginSamsungAirConditioner#4]
Many Thanks for your time and efforts on working on this plugin. 

Samsung app was so crappy, I had to login and put my credentials, every time I needed to remotely control it. I am so happy I'm not going to use it again!

As the title suggests is there room for any enhancement?

**Comment by peros550** [comment]
Hi Sebastian, 

I was working experimentally on a Homekit firmware for a ESP266 device. Basically, the firmware emulates a smart A/C with support for Homekit. For the moment, it does nothing else other than emulating a virtual A/C. 

The fan control can be added to the HeaterCooler device and homekit recognizes it as singe device exposing the fan control under the settings page of A/C. Then fan control is seated right under the oscillate control.

**Comment by SebastianOsinski** [comment]
You're right :) Somehow I didn't notice that HeaterCooler has RotationSpeed characteristic: https://github.com/KhaosT/HAP-NodeJS/blob/9eaea6df40811ccc71664a1ab0c13736e759dac7/lib/gen/HomeKitTypes.js#L2990
I'll surely add it in one of next releases.

**Comment by peros550** [comment]
thanks! you are great!
