### ISSUE TITLE
homebridge-samsung-ac-get-token gives SSL error

### ISSUE THREAD

**Issue by aramann** [SebastianOsinski/HomebridgePluginSamsungAirConditioner#46]
Hello, 

I'm getting this error when trying to get token: 

Error occured: C0178F15DC7F0000:error:0A00042E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1605:SSL alert number 70
<img width="1222" alt="Снимок экрана 2023-06-25 в 18 44 54" src="https://github.com/SebastianOsinski/HomebridgePluginSamsungAirConditioner/assets/18335371/41fa714c-12c8-4df9-9a32-91bc8a9eca79">

Also it seems that WindFree AC uses random port instead of 2878. I have a split system and one AC uses port 10711, other one uses 50244, it's the only open ports available

My exact models: ARO9TXFCAWKNEU and AR12TXFCAWKNEU

**Comment by SebastianOsinski** [comment]
Looks like these units are fairly new. Samsung Wi-Fi ACs seem to have couple "generations" which use different protocols for communicating. This plugin only supports the first generation which uses socket communication on 2878 port. I recommend looking for another plugin which works with your units' generation.

**Comment by aramann** [comment]
Thanks for the answer, will try to find a working plugin)
