### ISSUE TITLE
Home app shows heating mode as cooling

### ISSUE THREAD

**Issue by iJaffa** [SebastianOsinski/HomebridgePluginSamsungAirConditioner#5]
I have found that when I enable heat mode, the tile on the Home app reports 'Cooling to Xº'. Cool mode  correctly shows as 'Cooling to Xº'.

It appears to report the same incorrect information in the Home app even when using the remote to turn on the heating mode.

**Comment by iJaffa** [comment]
Sounds good, @SebastianOsinski. I'm very grateful for the work you're doing on this plugin. I just wish I had the time to contribute more to it!

**Comment by peros550** [comment]
Hi Sebastian, 

Does your updated code published today include optimizations for quicker response times ?

**Comment by SebastianOsinski** [comment]
@peros550 Not yet, I'm working on it right now :) Should take couple more days to test it and cover some edge cases.

**Comment by peros550** [comment]
I ‘ll try and let you know :)

**Comment by peros550** [comment]
Quick update:
The plugin became very responsive! You did some very good optimizations there! The whole Homebridge became more responsive for me as well. 

I tested the bug where messages (between heating/cooling) got messed so you may had set a heating mode and the home app was saying "cooling to X degrees". 

In all my tests I was messing around with Home app, changing values, modes etc and was looking at Samsung app to see what was the outcome and if the both apps were in sync. 

Here is a small issue I found.

It seems that the A/C tends to remember what was the last target temperature on every mode. Let's say that we use the A/C and set a target temperature for Cooling mode at 20C. Then we switch back to Heating mode and set a target temperature at 27C. All the previous actions could be handled by the remote or the Samsung App, it doesn't matter. 

Now we switch to the Home App. Let's say we set a heating mode and then select a new target temperature at i.e. 25C. Here is the thing. If you now switch the mode to Cooling, the home app will  continue showing the previous temp set within Home for heating (25C as per this example) , however if you go back at the Samsung app and check , it will show you a different temp which is the one it remembers for the Cooling mode. 

Of course, the moment you try to set a temperature, the A/C and the Home app get synced again!

**Comment by peros550** [comment]
Yes you are right. This is a bug at Samsung's side.
Have a nice day!

**Comment by iJaffa** [comment]
@SebastianOsinski I’ll install the beta and will let you know how it goes

**Comment by iJaffa** [comment]
@SebastianOsinski The beta is indeed much faster. One thing I have noticed is that it is not reading the current in-room temperature from the AC unit. Is this expected with this version?

**Comment by SebastianOsinski** [comment]
@iJaffa It should work as before (It works on my device). Does it display any in-room temperature, even invalid one or is there `--` instead of temp in Home app?

This version is much faster because once it fetches data from AC, it stores it locally and each time Home app asks for data, the data is immediately returned, without asking AC for it. Each time something on AC changes, e.g. when remote is used or in-door temp has changed, AC sends update to plugin which stores it and sends it to Home app.

One more question to both of you @iJaffa @peros550. Have you noticed in Homebridge logs constant disconnections from AC? In my case, plugin disconnects every 1-2h with either ETIMEDOUT or EHOSTUNREACH errors. It's either something with the plugin itself or with my setup (I suspect my RPi has faulty WiFi). I made some changes in the plugin, which makes it react to disconnections much faster (by default, socket created with Node JS notices disconnections after several minutes instead of seconds). This might also be the reason for that.

**Comment by iJaffa** [comment]
@SebastianOsinski After some observation, it appears to show the measured temperature from the last time which the Air Conditioner was running. I think that the A/C unit itself is caching the temperature value, since it appears to be consistent with the Samsung app as well.

I must say, the response time from the updated plugin is much faster, and it appears to be much more stable than the release build as well (always reports back, release build stops reporting back after a day or two).

I don't see any disconnections in my logs, but I don't have debug logging enabled. How can I check whether there are any disconnections or timeouts?

**Comment by peros550** [comment]
Hi Sebastian, I don't have a Putty connected to my RPi constantly. Is it possible to search logs instead?
Usually I run the following command:  "sudo journalctl -u homebridge.service -f" and get logs in real time. 
If there is any way to search logs created in the past while my PC was not connected to the RPi then let me know. 

Thanks

**Comment by SebastianOsinski** [comment]
@iJaffa If you don't see any disconnections in logs, then it's OK. They show by default, which means you don't experience any.

@peros550 You can check previous logs by running "sudo journalctl -u homebridge.service -n 100". This will print last 100 lines of log.

I migrated my whole homebridge setup to RPi 3 connected with ethernet cable and I still experience disconnections, sometimes they are permanent and only turning on the AC with remote fixes it. I have some idea what might be the culprit and will investigate more

**Comment by stalkerj** [comment]
How can i install beta?

**Comment by SebastianOsinski** [comment]
@stalkerj This post explains it: https://github.com/SebastianOsinski/HomebridgePluginSamsungAirConditioner/issues/5#issuecomment-433532032. To run commands as root user on Raspberry Pi you need to type `sudo su`. Then you can use command mentioned in that post

**Comment by stalkerj** [comment]
> @stalkerj This post explains it: [#5 (comment)](https://github.com/SebastianOsinski/HomebridgePluginSamsungAirConditioner/issues/5#issuecomment-433532032). To run commands as root user on Raspberry Pi you need to type `sudo su`. Then you can use command mentioned in that post

npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-515d1480': Permission denied

**Comment by SebastianOsinski** [comment]
This error shouldn't occur if you run `sudo su` and then `sudo npm install -g --unsafe-perm github:SebastianOsinski/HomebridgePluginSamsungAirConditioner#feature/v2`. This combo gives you basically all permissions available.

**Comment by SebastianOsinski** [comment]
Fixed in #11
